Window without table
NicoRodBilbao/StorioClient pull request #7
Opened 2023-01-26 13:12 UTC by mlnnzr

2023-01-26 13:19 UTC, joana-renteria requested changes

2023-01-26 13:19 UTC, joana-renteria commented on src/windowController/PackManagementWindowController.java
> +             * Set all combobox disabled
these are all javadoc comments, which should only be used for methods and classes, please make them normal comments with // or /*

2023-01-27 07:22 UTC, joana-renteria approved these changes

2023-01-27 12:25 UTC, NicoRodBilbao approved these changes
Looks good to me.

2023-01-27 12:28 UTC, Markelfdez approved these changes

2023-01-27 12:29 UTC, merged